//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Asortyment_sklepuEntities : DbContext
    {
        public Asortyment_sklepuEntities()
            : base("name=Asortyment_sklepuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dostawca> Dostawca { get; set; }
        public DbSet<Kategoria> Kategoria { get; set; }
        public DbSet<Kategoria_producent> Kategoria_producent { get; set; }
        public DbSet<Opis_produktu> Opis_produktu { get; set; }
        public DbSet<Producent> Producent { get; set; }
        public DbSet<Produkt> Produkt { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Zdjecie_produktu> Zdjecie_produktu { get; set; }
    }
}
