//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoria
    {
        public Kategoria()
        {
            this.Kategoria_producent = new HashSet<Kategoria_producent>();
        }
    
        public int id_kategorii { get; set; }
        public string nazwa_kategorii { get; set; }
    
        public virtual ICollection<Kategoria_producent> Kategoria_producent { get; set; }
    }
}
