//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opis_produktu
    {
        public Opis_produktu()
        {
            this.Produkt = new HashSet<Produkt>();
        }
    
        public int id_opisu { get; set; }
        public string opis { get; set; }
    
        public virtual ICollection<Produkt> Produkt { get; set; }
    }
}
